# Generated by Django 5.0.6 on 2024-06-13 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=255, unique=True), max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
