# Generated by Django 5.0.6 on 2024-06-13 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0002_document_slug_alter_document_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
